---
base: conventional_bninception_default.yaml

model:
  embedding_head:
    arch: GlobalPooling

    GeneralizedSumPooling:
      support_size: 64
      transport_ratio: 0.3
      entropy_regularizer_weight: 5.0
      augment_max_pool: true

loss:
  function: contrastive # contrastive, original_contrastive, triplet, multi_similarity, zero_shot_augmented, xbm
  xbm:
    function: original_contrastive
    batches_in_mem: 50
    start_at: 1000
    xbm_weight: 1.0
    pair_loss_weight: 1.0



training:
  early_stopping_patience: 15
  steps_per_epoch: 25
  classes_per_batch: 32
  sample_per_class: 4

optimizer:
  learning_rate: 1.0e-5
  learning_rate_scheduler:
    reduce_on_plateau:
      patience: 4




